[package]
name = "example_ggez"
version = "0.2.0"
authors = ["Enrico Benedetti <enrico_benedetti@yahoo.com>"]

[dependencies]
ggez = "0.6.1"
gfx = "0.18.1"

# for security alerts
nix = "0.20.2"
thread_local = "1.1.4"
regex = "1.5.5"
nalgebra = { version = "0.29", features = ["mint"] }
