[package]
name = "pathfinder"
version = "0.2.0"
authors = ["Enrico Benedetti <enrico_benedetti@yahoo.com>"]

[dependencies]
ggez = "0.7"
gfx = "0.18"
nalgebra = { version = "0.29", features = ["mint"] }
regex = "1.5"
