[package]
name = "example_ggez"
version = "0.2.0"
authors = ["Enrico Benedetti <enrico_benedetti@yahoo.com>"]

[dependencies]
ggez = "0.6.1"
gfx = "0.18.1"
nalgebra = { version = "0.29", features = ["mint"] }
